[package]
name = "hexadroid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev.package."*"]
opt-level = 3

[features]
inspector = ["bevy-inspector-egui"]

[dependencies]
bevy = { version = "0.7.0", features = ["dynamic"] }
bevy_rapier2d = "0.13.2"
bevy-inspector-egui = { version = "0.11.0", optional = true }
bevy_prototype_debug_lines = "0.7"
hexagon_tiles = "0.1.0"
